additions and changes

diff --git a/bin/bin/primary-screen b/bin/bin/primary-screen
--- a/bin/bin/primary-screen
+++ b/bin/bin/primary-screen
@@ -20,27 +20,27 @@ dialog=false
 primary_screen=''
 while getopts ":hdl" opt; do
     case ${opt} in
-	l)
-	    echo "Available screen:"
-	    xrandr | awk '/primary/{print $1}' | xargs -i% echo '%*'
-	    xrandr | grep -v 'primary' | awk '/ connected/{print $1}'
-	    exit 1
-	;;
-	h)
-	    displayUsage
-	    exit 1
-	    ;;
-	d)
-	    dialog=true
-	    ;;
-	\?)
-	    echo "Invalid option: $OPTARG" 1>&2
-	    exit 2
-	    ;;
-	:)
-	    echo "Invalid option: $OPTARG requires an argument" 1>&2
-	    exit 2
-	    ;;
+    l)
+        echo "Available screen:"
+        xrandr | awk '/primary/{print $1}' | xargs -i% echo '%*'
+        xrandr | grep -v 'primary' | awk '/ connected/{print $1}'
+        exit 1
+    ;;
+    h)
+        displayUsage
+        exit 1
+        ;;
+    d)
+        dialog=true
+        ;;
+    \?)
+        echo "Invalid option: $OPTARG" 1>&2
+        exit 2
+        ;;
+    :)
+        echo "Invalid option: $OPTARG requires an argument" 1>&2
+        exit 2
+        ;;
     esac
 done
 shift $((OPTIND-1))
@@ -57,7 +57,7 @@ fi
 if [ $# -lt 1 ] && ! $dialog
 then
     # if no input and no selection in dialogue use the screen with mouse in
-    primary_screen=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused == true) | .output')
+    primary_screen=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused == true).output')
 elif [ $# = 1 ]
 then
     # Use input
diff --git a/i3/.i3/i3exit b/i3/.i3/i3exit
--- a/i3/.i3/i3exit
+++ b/i3/.i3/i3exit
@@ -16,38 +16,38 @@ bettersuspend() {
 
 case "$1" in
     lock)
-	lock
-	;;
+    lock
+    ;;
     logout)
-	~/.i3/Scripts/i3-res save
-	sleep 2
-	i3-msg exit
-	;;
+    ~/.i3/Scripts/i3-res save
+    sleep 2
+    i3-msg exit
+    ;;
     switch_user)
-	dm-tool switch-to-greeter
-	;;
+    dm-tool switch-to-greeter
+    ;;
     suspend)
-	bettersuspend
-	;;
+    bettersuspend
+    ;;
     hibernate)
-	~/.i3/Scripts/i3-res save
-	sleep 2
-	systemctl hibernate -i && lock
-	;;
+    ~/.i3/Scripts/i3-res save
+    sleep 2
+    systemctl hibernate -i && lock
+    ;;
     reboot)
-	~/.i3/Scripts/i3-res save
-	sleep 2
-	$logind reboot
-	;;
+    ~/.i3/Scripts/i3-res save
+    sleep 2
+    $logind reboot
+    ;;
     shutdown)
-	~/.i3/Scripts/i3-res save
-	sleep 2
-	$logind poweroff
-	;;
+    ~/.i3/Scripts/i3-res save
+    sleep 2
+    $logind poweroff
+    ;;
     *)
-	echo "== ! i3exit: missing or invalid argument ! =="
-	echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
-	exit 2
+    echo "== ! i3exit: missing or invalid argument ! =="
+    echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
+    exit 2
 esac
 
 exit 0
