added path as necessary argument

diff --git a/i3/.i3/Scripts/feh-random-wallpaper b/i3/.i3/Scripts/feh-random-wallpaper
--- a/i3/.i3/Scripts/feh-random-wallpaper
+++ b/i3/.i3/Scripts/feh-random-wallpaper
@@ -2,6 +2,12 @@
 set -euo pipefail
 IFS=$'\n\t'
 
+if [ $# -lt 1 ]
+then
+    echo "argument 1 missing - path to wallpapers"
+    exit 1
+fi
+
 PATHTOIMAGES=$1
 if [ -d "$PATHTOIMAGES" ];
 then
