removed save and restore all

diff --git a/i3_manjaro/.i3/Scripts/i3-res b/i3_manjaro/.i3/Scripts/i3-res
--- a/i3_manjaro/.i3/Scripts/i3-res
+++ b/i3_manjaro/.i3/Scripts/i3-res
@@ -2,7 +2,11 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-
+# i3-res
+# script to utilize i3-ressurect to save all or restore all
+# argument 1  - [save/restore]
+# expected input/output - i3-res save -> Saves the all active workspaces to .i3/i3-resurrect
+# example suggested usage: i3-res save
 
 case $1 in
     save)
@@ -44,5 +48,8 @@ case $1 in
 
 	;;
     *)
-	notify-send "Else"
+	echo "Error: not a usable command"
+	exit 1
 esac
+
+exit 0
