made a cli for i3-res to easily save different workspaces into work, home etc.

diff --git a/i3_manjaro/.i3/Scripts/i3-res b/i3_manjaro/.i3/Scripts/i3-res
--- a/i3_manjaro/.i3/Scripts/i3-res
+++ b/i3_manjaro/.i3/Scripts/i3-res
@@ -8,7 +8,42 @@ IFS=$'\n\t'
 # expected input/output - i3-res save -> Saves the all active workspaces to .i3/i3-resurrect
 # example suggested usage: i3-res save
 
-case $1 in
+# Functions
+listLayouts() {
+    LAYOUTS=$(find . -type d -name 'i3-resurrect-*')
+    echo "Available layout(s):"
+    for layout in $LAYOUTS; do
+	echo "${layout#*-*-}"
+    done
+}
+
+
+# Set default params
+NAME="default"
+I3RESPATH=~/.i3/i3-resurrect
+
+# set params from argumements
+while getopts "i:ln:" opt; do
+    case ${opt} in
+	i)
+	    I3RESPATH=${OPTARG};;
+	l)
+	    listLayouts
+	    exit 0;;
+	n)
+	    NAME=${OPTARG};;
+	# TODO: h)
+	# echo "help text...."
+	\?)
+	    echo "Invalid option: $OPTARG" 1>&2;;
+	:)
+	    echo "Invalid option: $OPTARG requires an argument" 1>&2;;
+    esac
+done
+shift $((OPTIND -1))
+
+
+case ${@: -1} in
     save)
 	rm -f ~/.i3/i3-resurrect/*
 
@@ -25,14 +60,15 @@ case $1 in
 	    i3-resurrect save -w "$temp"
 	done
 
-	notify-send "i3-resurrect" "Saved all workspaces"
+	
+	notify-send "i3-resurrect" "Saved workspaces as \"$NAME\""
 
+	cp -r "$I3RESPATH" "$I3RESPATH-$NAME"
 	;;
     
     restore)
-	#save current workspace
-	cur_workspace=$(i3-msg -t get_workspaces | jq -r '.[] | select(.visible == true) | .name')
-
+	cp -r "$I3RESPATH-$NAME" "i3-resurrect"
+	
 	# extract workspace name which is defined between two underscored
 	workspaces=$(find ~/.i3/i3-resurrect/*.json | grep -Po '.*_\K(.*)_' | sed 's/_//' | uniq)
 	echo "Found workspaces: $workspaces"
@@ -44,11 +80,10 @@ case $1 in
 	done
 
 	notify-send "i3-resurrect" "Restored all workspaces"
-	i3-msg workspace "$cur_workspace"
 
 	;;
     *)
-	echo "Error: not a usable command"
+	echo "error: no operation specified (use -h for help)"
 	exit 1
 esac
 
