More stuff

diff --git a/i3/.i3/i3exit b/i3/.i3/i3exit
--- a/i3/.i3/i3exit
+++ b/i3/.i3/i3exit
@@ -2,12 +2,14 @@
 # /usr/bin/i3exit
 
 lock() {
-    playerctl pause
-    betterlockscreen -l dimblur -t "Don't you dare..."
+    playerctl -s pause
+    betterlockscreen -l dimblur --text "I take pictures :3"
 }
 
 bettersuspend() {
-    betterlockscreen -s -l dimblur
+    playerctl pause
+    amixer set Master mute
+    betterlockscreen -s -l dimblur --text "I take pictures :3"
 }
 # with openrc use loginctl
 [[ $(cat /proc/1/comm) = "systemd" ]] && logind=systemctl || logind=loginctl
@@ -15,37 +17,37 @@ bettersuspend() {
 case "$1" in
     lock)
 	lock
-        ;;
+	;;
     logout)
-        ~/.i3/Scripts/i3-res save
+	~/.i3/Scripts/i3-res save
 	sleep 2
 	i3-msg exit
-        ;;
+	;;
     switch_user)
-        dm-tool switch-to-greeter
-        ;;
+	dm-tool switch-to-greeter
+	;;
     suspend)
-        bettersuspend
-        ;;
+	bettersuspend
+	;;
     hibernate)
 	~/.i3/Scripts/i3-res save
 	sleep 2
-        systemctl hibernate -i && lock
-        ;;
+	systemctl hibernate -i && lock
+	;;
     reboot)
 	~/.i3/Scripts/i3-res save
 	sleep 2
-        $logind reboot
-        ;;
+	$logind reboot
+	;;
     shutdown)
 	~/.i3/Scripts/i3-res save
 	sleep 2
-        $logind poweroff
-        ;;
+	$logind poweroff
+	;;
     *)
-        echo "== ! i3exit: missing or invalid argument ! =="
-        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
-        exit 2
+	echo "== ! i3exit: missing or invalid argument ! =="
+	echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
+	exit 2
 esac
 
 exit 0
