massive updates and reorganization of config.org

diff --git a/emacs/.emacs.d/snippets/sh-mode/input b/emacs/.emacs.d/snippets/sh-mode/input
--- a/emacs/.emacs.d/snippets/sh-mode/input
+++ b/emacs/.emacs.d/snippets/sh-mode/input
@@ -4,36 +4,34 @@
 # --
 
 displayUsage() {
+# <>  angle brackets for required parameters: ping <hostname>
+# []  square brackets for optional parameters: mkdir [-p] <dirname>
+# ... ellipses for repeated items: cp <source1> [source2…] <dest>
+#  |  vertical bars for choice of items: netstat {-t|-u}
    echo '
-<>  angle brackets for required parameters: ping <hostname>
-[]  square brackets for optional parameters: mkdir [-p] <dirname>
-... ellipses for repeated items: cp <source1> [source2…] <dest>
- |  vertical bars for choice of items: netstat {-t|-u}
-
 usage:  name <operation> [...]
 operations:
-    name {-h help} shows this dialogue
-
+  name {-h help} shows this dialogue
 '
 }
 
 while getopts ":h${1:arg}$2" opt; do
-    case \$\{opt\} in
+	case \$\{opt\} in
 	$1)
-	    ;;
+		;;
 	h)
-	    displayUsage
-	    exit 1
-	    ;;
+		displayUsage
+		exit 1
+		;;
 	\?)
-	    echo "Invalid option: $OPTARG" 1>&2
-	    exit 2
-	    ;;
+		echo "Invalid option: $OPTARG" 1>&2
+		exit 2
+		;;
 	:)
-	    echo "Invalid option: $OPTARG requires an argument" 1>&2
-	    exit 2
-	    ;;
-    esac
+		echo "Invalid option: $OPTARG requires an argument" 1>&2
+		exit 2
+		;;
+	esac
 done
 
 shift $((OPTIND-1))
